create table public.follow_up (
  id serial not null,
  user_name text null,
  user_number text null,
  last_message timestamp without time zone null,
  created_at timestamp with time zone null default timezone ('America/Sao_Paulo'::text, now()),
  followup_10_sent boolean null default false,
  followup_30_sent boolean null default false,
  followup_180_sent boolean null default false,
  followup_1440_sent boolean null default false,
  followup_2880_sent boolean null default false,
  followup_4320_sent boolean null default false,
  followup_5760_sent boolean null default false,
  followup_7200_sent boolean null default false,
  followup_8640_sent boolean null default false,
  followup_11520_sent boolean null default false,
  followup_14400_sent boolean null default false,
  followup_15840_sent boolean null default false,
  followup_17280_sent boolean null default false,
  followup_18720_sent boolean null default false,
  followup_20160_sent boolean null default false,
  status text null default 'pendente'::text,
  constraint follow_up_pkey primary key (id),
  constraint follow_up_user_number_key unique (user_number)
) TABLESPACE pg_default;
