create table public.qualified_leads_jobs_offers (
  "Nome" text null,
  "Cargo" text null,
  "URL Linkedin" text null,
  "Sobre" text null,
  "Localidade" text null,
  "Empresa" text null,
  "URL Linkedin Empresa" text null,
  "Tempo na Empresa Atual" text null,
  "Colaboradores" text null,
  "Seguidores" text null,
  "Descript da Empresa" text null,
  "URL Empresa" text null,
  "Adress" text null,
  "Especialidades" text null,
  "Email" text null,
  id bigint not null,
  "URL Instagram" text null,
  "Mensagem Enviada Email" text null,
  "Mensagem Enviada LinkedIn" text null,
  "Data Mensagem LinkedIn" text null,
  "Data Mensagem Email" text null,
  "Conectado LinkedIn" boolean null,
  "Chat ID" text null,
  "Conexões" bigint null,
  "Provider ID" text null,
  "Telefone" text null,
  resposta_email text null,
  resposta_whatsapp text null,
  resposta_linkedin text null,
  resposta_instagram text null,
  "Setor" text null,
  "Outros Emails" text null,
  "Outros Telefones" text null,
  created_at timestamp with time zone null,
  mensagem_enviada_em text null,
  lead_score integer null default 0,
  constraint qualified_leads_jobs_offers_pkey primary key (id)
) TABLESPACE pg_default;